-- DROP TABLE IF EXISTS BANK_ACCOUNTS;
CREATE TABLE BANK_ACCOUNTS (
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    BANK_NAME VARCHAR(255) NOT NULL,
    AGENCY_NUMBER VARCHAR(255) NOT NULL,
    ACCOUNT VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT BANK_ACCOUNTS_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);