-- DROP TABLE IF EXISTS BOND_COURSE_CLASS;
CREATE TABLE BOND_COURSE_CLASS (
    BOND_ID bigint CHECK (BOND_ID > 0) NOT NULL,
    COURSE_CLASS_ID bigint CHECK (COURSE_CLASS_ID > 0) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (BOND_ID),
    CONSTRAINT BOND_COURSE_CLASS_BOND_ID_FOREIGN FOREIGN KEY (BOND_ID) REFERENCES BONDS (ID) ON DELETE CASCADE,
    CONSTRAINT BOND_COURSE_CLASS_COURSE_CLASS_ID_FOREIGN FOREIGN KEY (COURSE_CLASS_ID) REFERENCES COURSE_CLASSES (ID) ON DELETE CASCADE
);
CREATE INDEX BOND_COURSE_CLASS_COURSE_CLASS_ID_FOREIGN ON BOND_COURSE_CLASS (COURSE_CLASS_ID);