-- DROP TABLE IF EXISTS BOND_COURSE;
CREATE TABLE BOND_COURSE (
    BOND_ID bigint CHECK (BOND_ID > 0) NOT NULL,
    COURSE_ID bigint CHECK (COURSE_ID > 0) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (BOND_ID),
    CONSTRAINT BOND_COURSE_BOND_ID_FOREIGN FOREIGN KEY (BOND_ID) REFERENCES BONDS (ID) ON DELETE CASCADE,
    CONSTRAINT BOND_COURSE_COURSE_ID_FOREIGN FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID) ON DELETE CASCADE
);
CREATE INDEX BOND_COURSE_COURSE_ID_FOREIGN ON BOND_COURSE (COURSE_ID);