-- DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES (
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    COMPLEMENT VARCHAR(50) NOT NULL,
    number VARCHAR(5) NOT NULL,
    DISTRICT VARCHAR(50) NOT NULL,
    ZIP_CODE VARCHAR(8) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT ADDRESSES_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);