-- DROP TABLE IF EXISTS IDENTITIES;
CREATE TABLE IDENTITIES (
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    TYPE_ID bigint CHECK (TYPE_ID > 0) NOT NULL,
    number VARCHAR(15) NOT NULL,
    ISSUE_DATE date NOT NULL,
    ISSUER VARCHAR(10) NOT NULL,
    ISSUER_STATE VARCHAR(2) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT IDENTITIES_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE,
    CONSTRAINT IDENTITIES_TYPE_ID_FOREIGN FOREIGN KEY (TYPE_ID) REFERENCES DOCUMENT_TYPES (ID)
);
CREATE INDEX IDENTITIES_TYPE_ID_FOREIGN ON IDENTITIES (TYPE_ID);