-- DROP TABLE IF EXISTS PHONES;
CREATE SEQUENCE PHONES_SEQ;
CREATE TABLE PHONES (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('phones_seq'),
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    AREA_CODE VARCHAR(3) NOT NULL,
    number VARCHAR(12) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PHONES_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);
CREATE INDEX PHONES_EMPLOYEE_ID_FOREIGN ON PHONES (EMPLOYEE_ID);