-- DROP TABLE IF EXISTS MIGRATIONS;
CREATE SEQUENCE MIGRATIONS_SEQ;
CREATE TABLE MIGRATIONS (
    ID int CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('migrations_seq'),
    MIGRATION VARCHAR(255) NOT NULL,
    BATCH int NOT NULL,
    PRIMARY KEY (ID)
);
ALTER SEQUENCE MIGRATIONS_SEQ RESTART WITH 31;