-- DROP TABLE IF EXISTS PERSONAL_DETAILS;
CREATE TABLE PERSONAL_DETAILS (
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    JOB VARCHAR(50) NOT NULL,
    BIRTH_DATE date NOT NULL,
    BIRTH_STATE VARCHAR(2) NOT NULL,
    BIRTH_CITY VARCHAR(50) NOT NULL,
    MARITAL_STATUS VARCHAR(20) NOT NULL,
    FATHER_NAME VARCHAR(50) NOT NULL,
    MOTHER_NAME VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT PERSONAL_DETAILS_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);