-- DROP TABLE IF EXISTS INSTITUTIONAL_DETAILS;
CREATE TABLE INSTITUTIONAL_DETAILS (
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT INSTITUTIONAL_DETAILS_LOGIN_UNIQUE UNIQUE (LOGIN),
    CONSTRAINT INSTITUTIONAL_DETAILS_EMAIL_UNIQUE UNIQUE (EMAIL),
    CONSTRAINT INSTITUTIONAL_DETAILS_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);