-- DROP TABLE IF EXISTS NOTIFICATIONS;
CREATE TABLE NOTIFICATIONS (
    ID CHAR(36) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    NOTIFIABLE_TYPE VARCHAR(255) NOT NULL,
    NOTIFIABLE_ID bigint CHECK (NOTIFIABLE_ID > 0) NOT NULL,
    DATA text NOT NULL,
    READ_AT TIMESTAMP(0) NULL DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX NOTIFICATIONS_NOTIFIABLE_TYPE_NOTIFIABLE_ID_INDEX ON NOTIFICATIONS (NOTIFIABLE_TYPE, NOTIFIABLE_ID);