-- DROP TABLE IF EXISTS PASSWORD_RESETS;
CREATE TABLE PASSWORD_RESETS (
    EMAIL VARCHAR(255) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL
);
CREATE INDEX PASSWORD_RESETS_EMAIL_INDEX ON PASSWORD_RESETS (EMAIL);