-- DROP TABLE IF EXISTS SPOUSES;
CREATE TABLE SPOUSES (
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT SPOUSES_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);