-- DROP TABLE IF EXISTS BONDS;
CREATE SEQUENCE BONDS_SEQ;
CREATE TABLE BONDS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('bonds_seq'),
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) NOT NULL,
    ROLE_ID bigint CHECK (ROLE_ID > 0) NOT NULL,
    VOLUNTEER smallint NOT NULL DEFAULT '0',
    HIRING_PROCESS VARCHAR(10) NOT NULL,
    BEGIN date NOT NULL,
    TERMINATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BONDS_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID),
    CONSTRAINT BONDS_ROLE_ID_FOREIGN FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);
CREATE INDEX BONDS_EMPLOYEE_ID_FOREIGN ON BONDS (EMPLOYEE_ID);
CREATE INDEX BONDS_ROLE_ID_FOREIGN ON BONDS (ROLE_ID);