-- DROP TABLE IF EXISTS DOCUMENTS;
CREATE SEQUENCE DOCUMENTS_SEQ;
CREATE TABLE DOCUMENTS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('documents_seq'),
    FILE_NAME VARCHAR(255) NOT NULL,
    RELATED_TYPE VARCHAR(255) NOT NULL,
    RELATED_ID bigint CHECK (RELATED_ID > 0) NOT NULL,
    DOCUMENT_TYPE_ID bigint CHECK (DOCUMENT_TYPE_ID > 0) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    FILE_DATA bytea,
    PRIMARY KEY (ID),
    CONSTRAINT DOCUMENTS_DOCUMENT_TYPE_ID_FOREIGN FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPES (ID)
);
CREATE INDEX DOCUMENTS_RELATED_TYPE_RELATED_ID_INDEX ON DOCUMENTS (RELATED_TYPE, RELATED_ID);
CREATE INDEX DOCUMENTS_DOCUMENT_TYPE_ID_FOREIGN ON DOCUMENTS (DOCUMENT_TYPE_ID);