-- DROP TABLE IF EXISTS FAILED_JOBS;
CREATE SEQUENCE FAILED_JOBS_SEQ;
CREATE TABLE FAILED_JOBS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('failed_jobs_seq'),
    UUID VARCHAR(255) NOT NULL,
    CONNECTION text NOT NULL,
    QUEUE text NOT NULL,
    PAYLOAD text NOT NULL,
    EXCEPTION text NOT NULL,
    FAILED_AT TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FAILED_JOBS_UUID_UNIQUE UNIQUE (UUID)
);