-- DROP TABLE IF EXISTS BOND_POLE;
CREATE TABLE BOND_POLE (
    BOND_ID bigint CHECK (BOND_ID > 0) NOT NULL,
    POLE_ID bigint CHECK (POLE_ID > 0) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (BOND_ID),
    CONSTRAINT BOND_POLE_BOND_ID_FOREIGN FOREIGN KEY (BOND_ID) REFERENCES BONDS (ID) ON DELETE CASCADE,
    CONSTRAINT BOND_POLE_POLE_ID_FOREIGN FOREIGN KEY (POLE_ID) REFERENCES POLES (ID) ON DELETE CASCADE
);
CREATE INDEX BOND_POLE_POLE_ID_FOREIGN ON BOND_POLE (POLE_ID);