-- DROP TABLE IF EXISTS PERSONAL_ACCESS_TOKENS;
CREATE SEQUENCE PERSONAL_ACCESS_TOKENS_SEQ;
CREATE TABLE PERSONAL_ACCESS_TOKENS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('personal_access_tokens_seq'),
    TOKENABLE_TYPE VARCHAR(255) NOT NULL,
    TOKENABLE_ID bigint CHECK (TOKENABLE_ID > 0) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TOKEN VARCHAR(64) NOT NULL,
    ABILITIES text,
    LAST_USED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PERSONAL_ACCESS_TOKENS_TOKEN_UNIQUE UNIQUE (TOKEN)
);
CREATE INDEX PERSONAL_ACCESS_TOKENS_TOKENABLE_TYPE_TOKENABLE_ID_INDEX ON PERSONAL_ACCESS_TOKENS (TOKENABLE_TYPE, TOKENABLE_ID);