-- DROP TABLE IF EXISTS JOBS;
CREATE SEQUENCE JOBS_SEQ;
CREATE TABLE JOBS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('jobs_seq'),
    QUEUE VARCHAR(255) NOT NULL,
    PAYLOAD text NOT NULL,
    ATTEMPTS smallint CHECK (ATTEMPTS > 0) NOT NULL,
    RESERVED_AT int CHECK (RESERVED_AT > 0) DEFAULT NULL,
    AVAILABLE_AT int CHECK (AVAILABLE_AT > 0) NOT NULL,
    CREATED_AT int CHECK (CREATED_AT > 0) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX JOBS_QUEUE_INDEX ON JOBS (QUEUE);