-- DROP TABLE IF EXISTS QUALIFICATIONS;
CREATE TABLE QUALIFICATIONS (
    BOND_ID bigint CHECK (BOND_ID > 0) NOT NULL,
    KNOWLEDGE_AREA VARCHAR(255) NOT NULL,
    COURSE_NAME VARCHAR(255) NOT NULL,
    INSTITUTION_NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (BOND_ID),
    CONSTRAINT QUALIFICATIONS_BOND_ID_FOREIGN FOREIGN KEY (BOND_ID) REFERENCES BONDS (ID) ON DELETE CASCADE
);