-- DROP TABLE IF EXISTS IMPEDIMENTS;
CREATE SEQUENCE IMPEDIMENTS_SEQ;
CREATE TABLE IMPEDIMENTS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('impediments_seq'),
    BOND_ID bigint CHECK (BOND_ID > 0) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL DEFAULT 'Vínculo ainda não revisado',
    REVIEWER_ID bigint CHECK (REVIEWER_ID > 0) NOT NULL,
    CLOSED_BY_ID bigint CHECK (CLOSED_BY_ID > 0) DEFAULT NULL,
    CLOSED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IMPEDIMENTS_BOND_ID_FOREIGN FOREIGN KEY (BOND_ID) REFERENCES BONDS (ID) ON DELETE CASCADE,
    CONSTRAINT IMPEDIMENTS_CLOSED_BY_ID_FOREIGN FOREIGN KEY (CLOSED_BY_ID) REFERENCES USERS (ID),
    CONSTRAINT IMPEDIMENTS_REVIEWER_ID_FOREIGN FOREIGN KEY (REVIEWER_ID) REFERENCES USERS (ID)
);
CREATE INDEX IMPEDIMENTS_BOND_ID_FOREIGN ON IMPEDIMENTS (BOND_ID);
CREATE INDEX IMPEDIMENTS_REVIEWER_ID_FOREIGN ON IMPEDIMENTS (REVIEWER_ID);
CREATE INDEX IMPEDIMENTS_CLOSED_BY_ID_FOREIGN ON IMPEDIMENTS (CLOSED_BY_ID);