-- DROP TABLE IF EXISTS RESPONSIBILITIES;
CREATE SEQUENCE RESPONSIBILITIES_SEQ;
CREATE TABLE RESPONSIBILITIES (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('responsibilities_seq'),
    USER_ID bigint CHECK (USER_ID > 0) NOT NULL,
    USER_TYPE_ID bigint CHECK (USER_TYPE_ID > 0) NOT NULL,
    COURSE_ID bigint CHECK (COURSE_ID > 0) DEFAULT NULL,
    BEGIN_DATE date NOT NULL DEFAULT '2022-11-30',
    END_DATE date DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT RESPONSIBILITIES_USER_ID_USER_TYPE_ID_COURSE_ID_UNIQUE UNIQUE (USER_ID, USER_TYPE_ID, COURSE_ID),
    CONSTRAINT RESPONSIBILITIES_COURSE_ID_FOREIGN FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID),
    CONSTRAINT RESPONSIBILITIES_USER_ID_FOREIGN FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT RESPONSIBILITIES_USER_TYPE_ID_FOREIGN FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPES (ID)
);
CREATE INDEX RESPONSIBILITIES_USER_TYPE_ID_FOREIGN ON RESPONSIBILITIES (USER_TYPE_ID);
CREATE INDEX RESPONSIBILITIES_COURSE_ID_FOREIGN ON RESPONSIBILITIES (COURSE_ID);