-- DROP TABLE IF EXISTS COURSE_CLASSES;
CREATE SEQUENCE COURSE_CLASSES_SEQ;
CREATE TABLE COURSE_CLASSES (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('course_classes_seq'),
    COURSE_ID bigint CHECK (COURSE_ID > 0) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CPP VARCHAR(255) DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT COURSE_CLASSES_CODE_UNIQUE UNIQUE (CODE),
    CONSTRAINT COURSE_CLASSES_COURSE_ID_FOREIGN FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID)
);
CREATE INDEX COURSE_CLASSES_COURSE_ID_FOREIGN ON COURSE_CLASSES (COURSE_ID);