-- DROP TABLE IF EXISTS USERS;
CREATE SEQUENCE USERS_SEQ;
CREATE TABLE USERS (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('users_seq'),
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    ACTIVE smallint NOT NULL DEFAULT '0',
    EMAIL_VERIFIED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    EMPLOYEE_ID bigint CHECK (EMPLOYEE_ID > 0) DEFAULT NULL,
    REMEMBER_TOKEN VARCHAR(100) DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT USERS_LOGIN_UNIQUE UNIQUE (LOGIN),
    CONSTRAINT USERS_EMPLOYEE_ID_UNIQUE UNIQUE (EMPLOYEE_ID),
    CONSTRAINT USERS_EMPLOYEE_ID_FOREIGN FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);