-- DROP TABLE IF EXISTS ACTIVITY_LOG;
CREATE SEQUENCE ACTIVITY_LOG_SEQ;
CREATE TABLE ACTIVITY_LOG (
    ID bigint CHECK (ID > 0) NOT NULL DEFAULT NEXTVAL ('activity_log_seq'),
    LOG_NAME VARCHAR(255) DEFAULT NULL,
    DESCRIPTION text NOT NULL,
    SUBJECT_TYPE VARCHAR(255) DEFAULT NULL,
    SUBJECT_ID bigint CHECK (SUBJECT_ID > 0) DEFAULT NULL,
    EVENT VARCHAR(255) DEFAULT NULL,
    CAUSER_TYPE VARCHAR(255) DEFAULT NULL,
    CAUSER_ID bigint CHECK (CAUSER_ID > 0) DEFAULT NULL,
    PROPERTIES JSON DEFAULT NULL,
    BATCH_UUID CHAR(36) DEFAULT NULL,
    CREATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL,
    PRIMARY KEY (ID)
);
CREATE INDEX SUBJECT ON ACTIVITY_LOG (SUBJECT_TYPE, SUBJECT_ID);
CREATE INDEX CAUSER ON ACTIVITY_LOG (CAUSER_TYPE, CAUSER_ID);
CREATE INDEX ACTIVITY_LOG_LOG_NAME_INDEX ON ACTIVITY_LOG (LOG_NAME);